// this code is autogenerated, do not check it into to your code repository

// ref lib/elixir_opentui/nif.ex:14
const std = @import("std");
const beam = @import("beam");
const root = @import("root");

const Allocator = std.mem.Allocator;
const ByteList = std.ArrayList(u8);
const TermList = std.ArrayList(beam.term);
const char_bytes_size = 64;

// ── Cell: terminal cell with UTF-8 grapheme payload ──────────────────────
pub const Cell = extern struct {
    char_bytes: [char_bytes_size]u8, // UTF-8, null-padded
    char_len: u8,                    // 0-64
    fg: [3]u8,          // RGB
    bg: [3]u8,          // RGB
    attrs: u8,          // bits: bold(0), italic(1), underline(2), strikethrough(3), dim(4), inverse(5)
    hit_id: u16,        // 0=none, 1..65535=mapped atom
    _pad: [2]u8,

    pub fn blank() Cell {
        var char_bytes = [_]u8{0} ** char_bytes_size;
        char_bytes[0] = ' ';

        return Cell{
            .char_bytes = char_bytes,
            .char_len = 1,
            .fg = [_]u8{ 255, 255, 255 },
            .bg = [_]u8{ 0, 0, 0 },
            .attrs = 0,
            .hit_id = 0,
            ._pad = [_]u8{ 0, 0 },
        };
    }

    pub fn eql(a: Cell, b: Cell) bool {
        const a_bytes: *const [@sizeOf(Cell)]u8 = @ptrCast(&a);
        const b_bytes: *const [@sizeOf(Cell)]u8 = @ptrCast(&b);
        return std.mem.eql(u8, a_bytes, b_bytes);
    }
};

// ── FrameBuffer: double-buffered cell grid ───────────────────────────────
const FrameBufferData = struct {
    cols: u32,
    rows: u32,
    front: []Cell,
    back: []Cell,
};

pub const FrameBuffer = beam.Resource(FrameBufferData, root, .{});

fn alloc_cells(gpa: Allocator, count: usize) ![]Cell {
    const cells = try gpa.alloc(Cell, count);
    const b = Cell.blank();
    for (cells) |*c| {
        c.* = b;
    }
    return cells;
}

// ── NIF: init(cols, rows) → FrameBuffer resource ────────────────────────
pub fn init(cols: u32, rows: u32) !FrameBuffer {
    const gpa = beam.allocator;
    const count: usize = @as(usize, cols) * @as(usize, rows);
    const front = try alloc_cells(gpa, count);
    const back = try alloc_cells(gpa, count);

    return FrameBuffer.create(.{
        .cols = cols,
        .rows = rows,
        .front = front,
        .back = back,
    }, .{});
}

// ── NIF: clear(fb) → :ok ────────────────────────────────────────────────
pub fn clear(fb: FrameBuffer) void {
    const data = fb.unpack();
    const b = Cell.blank();
    for (data.back) |*c| {
        c.* = b;
    }
}

// ── NIF: get_cell_data(fb, x, y) → {char_bin, fg_r, fg_g, fg_b, bg_r, bg_g, bg_b, attrs, hit_id}
pub fn get_cell_data(fb: FrameBuffer, x: u32, y: u32) beam.term {
    const data = fb.unpack();
    if (x >= data.cols or y >= data.rows) {
        return beam.make(.nil, .{});
    }
    const idx = @as(usize, y) * @as(usize, data.cols) + @as(usize, x);
    const cell = data.front[idx];
    const char_len = @min(@as(usize, cell.char_len), cell.char_bytes.len);
    const char_slice = cell.char_bytes[0..char_len];

    return beam.make(.{
        char_slice,
        @as(u8, cell.fg[0]),
        @as(u8, cell.fg[1]),
        @as(u8, cell.fg[2]),
        @as(u8, cell.bg[0]),
        @as(u8, cell.bg[1]),
        @as(u8, cell.bg[2]),
        cell.attrs,
        cell.hit_id,
    }, .{});
}

// ── NIF: put_cells(fb, binary) → :ok ────────────────────────────────────
// Batch binary protocol:
//   CELL: <<1, x::16-le, y::16-le, char_len, char[64], fg[3], bg[3], attrs, hit_id::16-le>> = 79 bytes total
//   FILL: <<2, x::16-le, y::16-le, w::16-le, h::16-le, char_len, char[64], fg[3], bg[3], attrs>> = 81 bytes total
//   HIT:  <<3, x::16-le, y::16-le, w::16-le, h::16-le, hit_id::16-le>> = 11 bytes
pub fn put_cells(fb: FrameBuffer, binary: []const u8) void {
    const data = fb.unpack();
    const cols = data.cols;
    const rows = data.rows;
    const back = data.back;
    var pos: usize = 0;

    while (pos < binary.len) {
        const tag = binary[pos];
        pos += 1;

        switch (tag) {
            1 => { // CELL: 78 bytes after tag
                if (pos + 78 > binary.len) return;
                const x = std.mem.readInt(u16, binary[pos..][0..2], .little);
                const y = std.mem.readInt(u16, binary[pos + 2..][0..2], .little);
                const char_len = binary[pos + 4];
                if (x < cols and y < rows) {
                    const idx = @as(usize, y) * @as(usize, cols) + @as(usize, x);
                    back[idx] = Cell{
                        .char_bytes = binary[pos + 5..][0..char_bytes_size].*,
                        .char_len = @min(char_len, @as(u8, char_bytes_size)),
                        .fg = binary[pos + 69..][0..3].*,
                        .bg = binary[pos + 72..][0..3].*,
                        .attrs = binary[pos + 75],
                        .hit_id = std.mem.readInt(u16, binary[pos + 76..][0..2], .little),
                        ._pad = [_]u8{ 0, 0 },
                    };
                }
                pos += 78;
            },
            2 => { // FILL: 80 bytes after tag
                if (pos + 80 > binary.len) return;
                const x = std.mem.readInt(u16, binary[pos..][0..2], .little);
                const y = std.mem.readInt(u16, binary[pos + 2..][0..2], .little);
                const w = std.mem.readInt(u16, binary[pos + 4..][0..2], .little);
                const h = std.mem.readInt(u16, binary[pos + 6..][0..2], .little);
                const char_len = binary[pos + 8];
                const char_bytes = binary[pos + 9..][0..char_bytes_size].*;
                const fg = binary[pos + 73..][0..3].*;
                const bg = binary[pos + 76..][0..3].*;
                const attrs_val = binary[pos + 79];

                const cell = Cell{
                    .char_bytes = char_bytes,
                    .char_len = @min(char_len, @as(u8, char_bytes_size)),
                    .fg = fg,
                    .bg = bg,
                    .attrs = attrs_val,
                    .hit_id = 0,
                    ._pad = [_]u8{ 0, 0 },
                };

                var cy: u32 = y;
                while (cy < y + h and cy < rows) : (cy += 1) {
                    var cx: u32 = x;
                    while (cx < x + w and cx < cols) : (cx += 1) {
                        const idx = @as(usize, cy) * @as(usize, cols) + @as(usize, cx);
                        back[idx] = cell;
                    }
                }
                pos += 80;
            },
            3 => { // HIT: 10 bytes after tag
                if (pos + 10 > binary.len) return;
                const x = std.mem.readInt(u16, binary[pos..][0..2], .little);
                const y = std.mem.readInt(u16, binary[pos + 2..][0..2], .little);
                const w = std.mem.readInt(u16, binary[pos + 4..][0..2], .little);
                const h = std.mem.readInt(u16, binary[pos + 6..][0..2], .little);
                const hit_id = std.mem.readInt(u16, binary[pos + 8..][0..2], .little);

                var cy: u32 = y;
                while (cy < y + h and cy < rows) : (cy += 1) {
                    var cx: u32 = x;
                    while (cx < x + w and cx < cols) : (cx += 1) {
                        const idx = @as(usize, cy) * @as(usize, cols) + @as(usize, cx);
                        back[idx].hit_id = hit_id;
                    }
                }
                pos += 10;
            },
            else => return,
        }
    }
}

// ── NIF: render_frame_capture(fb) → binary ──────────────────────────────
pub fn render_frame_capture(fb: FrameBuffer) ![]u8 {
    const gpa = beam.allocator;
    var data = fb.unpack();
    const cols = data.cols;
    const rows = data.rows;
    const count = @as(usize, cols) * @as(usize, rows);

    var output: ByteList = .{};
    defer output.deinit(gpa);

    var cur_fg: [3]u8 = [_]u8{ 255, 255, 255 };
    var cur_bg: [3]u8 = [_]u8{ 0, 0, 0 };
    var cur_attrs: u8 = 0;
    var sgr_initialized = false;

    var i: usize = 0;
    while (i < count) : (i += 1) {
        if (!Cell.eql(data.front[i], data.back[i])) {
            const x: u32 = @intCast(i % @as(usize, cols));
            const y: u32 = @intCast(i / @as(usize, cols));
            const cell = data.back[i];
            const char_len = @min(@as(usize, cell.char_len), cell.char_bytes.len);

            try write_cursor_move(gpa, &output, x + 1, y + 1);

            if (!sgr_initialized or
                !std.mem.eql(u8, &cur_fg, &cell.fg) or
                !std.mem.eql(u8, &cur_bg, &cell.bg) or
                cur_attrs != cell.attrs)
            {
                try write_sgr(gpa, &output, cell.fg, cell.bg, cell.attrs);
                cur_fg = cell.fg;
                cur_bg = cell.bg;
                cur_attrs = cell.attrs;
                sgr_initialized = true;
            }

            try output.appendSlice(gpa, cell.char_bytes[0..char_len]);
        }
    }

    if (sgr_initialized) {
        try output.appendSlice(gpa, "\x1b[0m");
    }

    // Swap front and back, write back to resource
    const temp = data.front;
    data.front = data.back;
    data.back = temp;
    fb.update(data);

    // Return owned copy
    const result = try gpa.alloc(u8, output.items.len);
    @memcpy(result, output.items);
    return result;
}

// ── NIF: render_frame(fb) → :ok ─────────────────────────────────────────
pub fn render_frame(fb: FrameBuffer) !void {
    const gpa = beam.allocator;
    var data = fb.unpack();
    const cols = data.cols;
    const rows = data.rows;
    const count = @as(usize, cols) * @as(usize, rows);

    var output: ByteList = .{};
    defer output.deinit(gpa);

    var cur_fg: [3]u8 = [_]u8{ 255, 255, 255 };
    var cur_bg: [3]u8 = [_]u8{ 0, 0, 0 };
    var cur_attrs: u8 = 0;
    var sgr_initialized = false;

    var i: usize = 0;
    while (i < count) : (i += 1) {
        if (!Cell.eql(data.front[i], data.back[i])) {
            const x: u32 = @intCast(i % @as(usize, cols));
            const y: u32 = @intCast(i / @as(usize, cols));
            const cell = data.back[i];
            const char_len = @min(@as(usize, cell.char_len), cell.char_bytes.len);

            try write_cursor_move(gpa, &output, x + 1, y + 1);

            if (!sgr_initialized or
                !std.mem.eql(u8, &cur_fg, &cell.fg) or
                !std.mem.eql(u8, &cur_bg, &cell.bg) or
                cur_attrs != cell.attrs)
            {
                try write_sgr(gpa, &output, cell.fg, cell.bg, cell.attrs);
                cur_fg = cell.fg;
                cur_bg = cell.bg;
                cur_attrs = cell.attrs;
                sgr_initialized = true;
            }

            try output.appendSlice(gpa, cell.char_bytes[0..char_len]);
        }
    }

    if (sgr_initialized) {
        try output.appendSlice(gpa, "\x1b[0m");
    }

    // Write to stdout via POSIX fd
    var written: usize = 0;
    while (written < output.items.len) {
        const result = try std.posix.write(std.posix.STDOUT_FILENO, output.items[written..]);
        written += result;
    }

    // Swap front and back, write back to resource
    const temp = data.front;
    data.front = data.back;
    data.back = temp;
    fb.update(data);
}

// ── NIF: resize(fb, cols, rows) → :ok ───────────────────────────────────
pub fn resize(fb: FrameBuffer, cols: u32, rows: u32) !void {
    const gpa = beam.allocator;
    var data = fb.unpack();
    const count = @as(usize, cols) * @as(usize, rows);

    gpa.free(data.front);
    gpa.free(data.back);

    data.front = try alloc_cells(gpa, count);
    data.back = try alloc_cells(gpa, count);
    data.cols = cols;
    data.rows = rows;
    fb.update(data);
}

// ── NIF: get_hit_id(fb, x, y) → u16 | nil ──────────────────────────────
pub fn get_hit_id(fb: FrameBuffer, x: u32, y: u32) beam.term {
    const data = fb.unpack();
    if (x >= data.cols or y >= data.rows) {
        return beam.make(.nil, .{});
    }
    const idx = @as(usize, y) * @as(usize, data.cols) + @as(usize, x);
    const hit = data.front[idx].hit_id;
    if (hit == 0) {
        return beam.make(.nil, .{});
    }
    return beam.make(hit, .{});
}

// ── NIF: to_strings(fb) → [String.t()] ─────────────────────────────────
pub fn to_strings(fb: FrameBuffer) !beam.term {
    const gpa = beam.allocator;
    const data = fb.unpack();
    const cols = data.cols;
    const rows = data.rows;

    var result_list: TermList = .{};
    defer result_list.deinit(gpa);

    var y: u32 = 0;
    while (y < rows) : (y += 1) {
        var row_buf: ByteList = .{};
        defer row_buf.deinit(gpa);

        var x: u32 = 0;
        while (x < cols) : (x += 1) {
            const idx = @as(usize, y) * @as(usize, cols) + @as(usize, x);
            const cell = data.front[idx];
            const char_len = @min(@as(usize, cell.char_len), cell.char_bytes.len);
            try row_buf.appendSlice(gpa, cell.char_bytes[0..char_len]);
        }

        try result_list.append(gpa, beam.make(row_buf.items, .{}));
    }

    return beam.make(result_list.items, .{});
}

// ── NIF: draw_char_blend(fb, x, y, char_len, char[64], fg[3], bg[3]) → :ok ──
pub fn draw_char_blend(fb: FrameBuffer, x: u32, y: u32, char_len: u8, char_bytes: [char_bytes_size]u8, fg: [3]u8, bg: [3]u8) void {
    const data = fb.unpack();
    if (x >= data.cols or y >= data.rows) return;
    const idx = @as(usize, y) * @as(usize, data.cols) + @as(usize, x);
    data.back[idx] = Cell{
        .char_bytes = char_bytes,
        .char_len = @min(char_len, @as(u8, char_bytes_size)),
        .fg = fg,
        .bg = bg,
        .attrs = 0,
        .hit_id = data.back[idx].hit_id,
        ._pad = [_]u8{ 0, 0 },
    };
}

// ── ANSI helpers ────────────────────────────────────────────────────────
fn write_cursor_move(gpa: Allocator, output: *ByteList, x: u32, y: u32) !void {
    try output.appendSlice(gpa, "\x1b[");
    try write_u32(gpa, output, y);
    try output.append(gpa, ';');
    try write_u32(gpa, output, x);
    try output.append(gpa, 'H');
}

fn write_sgr(gpa: Allocator, output: *ByteList, fg: [3]u8, bg: [3]u8, attrs: u8) !void {
    try output.appendSlice(gpa, "\x1b[0");

    if (attrs & 1 != 0) try output.appendSlice(gpa, ";1");
    if (attrs & 16 != 0) try output.appendSlice(gpa, ";2");
    if (attrs & 2 != 0) try output.appendSlice(gpa, ";3");
    if (attrs & 4 != 0) try output.appendSlice(gpa, ";4");
    if (attrs & 64 != 0) try output.appendSlice(gpa, ";5");
    if (attrs & 32 != 0) try output.appendSlice(gpa, ";7");
    if (attrs & 128 != 0) try output.appendSlice(gpa, ";8");
    if (attrs & 8 != 0) try output.appendSlice(gpa, ";9");

    try output.appendSlice(gpa, ";38;2;");
    try write_u32(gpa, output, fg[0]);
    try output.append(gpa, ';');
    try write_u32(gpa, output, fg[1]);
    try output.append(gpa, ';');
    try write_u32(gpa, output, fg[2]);

    try output.appendSlice(gpa, ";48;2;");
    try write_u32(gpa, output, bg[0]);
    try output.append(gpa, ';');
    try write_u32(gpa, output, bg[1]);
    try output.append(gpa, ';');
    try write_u32(gpa, output, bg[2]);

    try output.append(gpa, 'm');
}

fn write_u32(gpa: Allocator, output: *ByteList, value: anytype) !void {
    var buf: [10]u8 = undefined;
    const v: u32 = @intCast(value);
    var len: usize = 0;

    if (v == 0) {
        try output.append(gpa, '0');
        return;
    }

    var n = v;
    while (n > 0) : (n /= 10) {
        buf[len] = @intCast(n % 10 + '0');
        len += 1;
    }

    var i: usize = 0;
    while (i < len) : (i += 1) {
        try output.append(gpa, buf[len - 1 - i]);
    }
}
